config/routes.rb
SnowSample::Application.routes.draw do
  resources :followers

  resources :tweepsters

  root :to => 'tweepsters#index'

end

app/models/follower.rb
class Follower < ActiveRecord::Base
  attr_accessible :tweepster_id, :twitter_id

  belongs_to :tweepster
end

app/models/tweepster.rb
class Tweepster < ActiveRecord::Base
  attr_accessible :twitter_id, :username, :cursor

  has_many :followers

  def follower_count
    # Cache the value of the follower count. This is refreshed once per hour:
  	Rails.cache.fetch("#{username}.follower_count-#{Time.now.strftime("%y%m%d%H")}") do
      Twitter.user(username).followers_count
    end
  end

  def save_followers
    # Check to see if we have made it through all the pages of followers yet:
    if cursor.nonzero?
      # Get the next 5k followers:
      fids = Twitter.follower_ids(username, cursor: cursor)

      # Pair up the new ids with this tweepster's database id. The pair is what is inserted to the db:
      sql_pairs = fids.ids.map{ |fid| "(#{fid}, #{id})" }

      # Break into groups of 500 at a time, and do 10 big honking bulk insert to cover all 5k ids:
      sql_pairs.in_groups_of(500, false) do |id_pairs|
        # the INGORE option to the INSERT sql command is MySQL only, and silences dup-key errors:
        Follower.connection.execute("INSERT IGNORE INTO followers (twitter_id, tweepster_id) VALUES #{id_pairs.join(',')}")
      end

      # Remember the page we are on, so we can resume on the next request:
      update_attribute(:cursor, fids.next_cursor)
    end
  end
end

app/models/voting_advice.rb
class VotingAdvice < ActiveRecord::Base
  attr_accessible :text, :sent_at, :twitter_id
  # not sure if I need this any more... attr_accessible :to
  def post!
    Twitter.post!(twitter_id, "You vote here <url, etc>")
    update_attribute :sent_at, Time.now
  rescue TwitterException 
    # log
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  # GET /followers
  # GET /followers.json
  def index
    @followers = Follower.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @followers }
    end
  end

  # GET followers/1
  # GET /followers/1.json
  def show
    @follower = Follower.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @follower }
    end
  end

  # GET /followers/new
  # GET /followers/new.json
  def new
    @follower = Follower.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @follower }
    end
  end

  # GET /followers/1/edit
  def edit
    @follower = Follower.find(params[:id])
  end

  # POST /followers
  # POST /followers.json
  def create
    @follower = Follower.new(params[:follower])

    respond_to do |format|
      if @follower.save
        format.html { redirect_to @follower, notice: 'Follower was successfully created.' }
        format.json { render json: @follower, status: :created, location: @follower }
      else
        format.html { render action: "new" }
        format.json { render json: @follower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /followers/1
  # PUT /followers/1.json
  def update
    @follower = Follower.find(params[:id])

    respond_to do |format|
      if @follower.update_attributes(params[:follower])
        format.html { redirect_to @follower, notice: 'Follower was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @follower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /followers/1
  # DELETE /followers/1.json
  def destroy
    @follower = Follower.find(params[:id])
    @follower.destroy

    respond_to do |format|
      format.html { redirect_to followers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tweepsters_controller.rb
class TweepstersController < ApplicationController
  # GET /tweepsters
  # GET /tweepsters.json
  def index
    @tweepsters = Tweepster.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweepsters }
    end
  end

  # GET /tweepsters/1
  # GET /tweepsters/1.json
  def show
    @tweepster = Tweepster.find(params[:id])
    @tweepster.save_followers

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweepster }
    end
  end

  # GET /tweepsters/new
  # GET /tweepsters/new.json
  def new
    @tweepster = Tweepster.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweepster }
    end
  end

  # GET /tweepsters/1/edit
  def edit
    @tweepster = Tweepster.find(params[:id])
  end

  # POST /tweepsters
  # POST /tweepsters.json
  def create
    @tweepster = Tweepster.new(params[:tweepster])

    respond_to do |format|
      if @tweepster.save
        format.html { redirect_to @tweepster, notice: 'Tweepster was successfully created.' }
        format.json { render json: @tweepster, status: :created, location: @tweepster }
      else
        format.html { render action: "new" }
        format.json { render json: @tweepster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweepsters/1
  # PUT /tweepsters/1.json
  def update
    @tweepster = Tweepster.find(params[:id])

    respond_to do |format|
      if @tweepster.update_attributes(params[:tweepster])
        format.html { redirect_to @tweepster, notice: 'Tweepster was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweepster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweepsters/1
  # DELETE /tweepsters/1.json
  def destroy
    @tweepster = Tweepster.find(params[:id])
    @tweepster.destroy

    respond_to do |format|
      format.html { redirect_to tweepsters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/tweepsters_helper.rb
module TweepstersHelper
end

app/views/followers/_form.html.erb
<%= form_for(@follower) do |f| %>
  <% if @follower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@follower.errors.count, "error") %> prohibited this follower from being saved:</h2>

      <ul>
      <% @follower.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :twitter_id %><br />
    <%= f.text_field :twitter_id %>
  </div>
  <div class="field">
    <%= f.label :tweepster_id %><br />
    <%= f.number_field :tweepster_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/followers/edit.html.erb
<h1>Editing follower</h1>

<%= render 'form' %>

<%= link_to 'Show', @follower %> |
<%= link_to 'Back', followers_path %>

app/views/followers/index.html.erb
<h1>Listing followers</h1>

<table>
  <tr>
    <th>Twitter</th>
    <th>Tweepster</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @followers.each do |follower| %>
  <tr>
    <td><%= follower.twitter_id %></td>
    <td><%= follower.tweepster_id %></td>
    <td><%= link_to 'Show', follower %></td>
    <td><%= link_to 'Edit', edit_follower_path(follower) %></td>
    <td><%= link_to 'Destroy', follower, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Follower', new_follower_path %>

app/views/followers/new.html.erb
<h1>New follower</h1>

<%= render 'form' %>

<%= link_to 'Back', followers_path %>

app/views/followers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Twitter:</b>
  <%= @follower.twitter_id %>
</p>

<p>
  <b>Tweepster:</b>
  <%= @follower.tweepster_id %>
</p>


<%= link_to 'Edit', edit_follower_path(@follower) %> |
<%= link_to 'Back', followers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SnowSample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :header %>
</head>
<body>

  <%= yield %>

  <footer>
  	<%= Twitter.rate_limit_status.remaining_hits.to_s + " Twitter API request(s)   remaining this hour" %>
  </footer>
</body>
</html>

app/views/tweepsters/_form.html.erb
<%= form_for(@tweepster) do |f| %>
  <% if @tweepster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweepster.errors.count, "error") %> prohibited this tweepster from being saved:</h2>

      <ul>
      <% @tweepster.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :cursor %><br />
    <%= f.text_field :cursor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweepsters/edit.html.erb
<h1>Editing tweepster</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweepster %> |
<%= link_to 'Back', tweepsters_path %>

app/views/tweepsters/index.html.erb
<h1>Listing tweepsters</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Followers</th>
    <th>Collected</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tweepsters.each do |tweepster| %>
  <tr>
    <td><%= tweepster.username %></td>
    <td><%= tweepster.follower_count %></td>
    <td><%= tweepster.followers.size %></td>
    <td><%= link_to 'Show', tweepster %></td>
    <td><%= link_to 'Edit', edit_tweepster_path(tweepster) %></td>
    <td><%= link_to 'Destroy', tweepster, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tweepster', new_tweepster_path %>

app/views/tweepsters/new.html.erb
<h1>New tweepster</h1>

<%= render 'form' %>

<%= link_to 'Back', tweepsters_path %>

app/views/tweepsters/show.html.erb
<% content_for :header do %>
  <META HTTP-EQUIV=Refresh CONTENT="1">
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @tweepster.username %>
</p>

<p>
  <b>Total Followers (updated hourly):</b>
  <%= @tweepster.follower_count %>
</p>

<p>
  <b>Collected Followers:</b>
  <%= @tweepster.followers.count %>
</p>

<p>
  <b>Cursor Position:</b>
  <%= @tweepster.cursor %>
</p>


<%= link_to 'Edit', edit_tweepster_path(@tweepster) %> |
<%= link_to 'Back', tweepsters_path %>